version: "3.9.10"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      BOT_TOKEN: $BOT_TOKEN
      DATABASE_URL: $DATABASE_URL  # defaults to None
      HU_STRING_SESSION: $HU_STRING_SESSION
